name: internhub
description: "A Mobile Application about Intern Hub."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0
  firebase_storage: ^12.3.1
  flutter_facebook_auth: ^7.1.1
  modal_progress_hud_nsn: ^0.5.1
  google_fonts: ^6.2.1
  awesome_dialog: ^3.1.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  validators: ^3.0.0
  fluttertoast: ^8.2.6
  provider: ^6.0.3
  local_auth: ^2.1.7
  shared_preferences: ^2.3.2
  firebase_database: ^11.1.2
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.0.20
  searchfield: ^1.1.6
  connectivity_plus: ^3.0.0
  http: ^1.2.2

  # New dependencies for profile functionality
  image_picker: ^0.8.7+3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package to enforce best practices
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
