// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4O-U9xtgLRDVHFETlg36cYC24hQ3wkQ',
    appId: '1:238945027859:web:9a19b8c97390d471a2bce6',
    messagingSenderId: '238945027859',
    projectId: 'internhub-25577',
    authDomain: 'internhub-25577.firebaseapp.com',
    databaseURL: 'https://internhub-25577-default-rtdb.firebaseio.com',
    storageBucket: 'internhub-25577.appspot.com',
    measurementId: 'G-2N5D2J7PG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtM_upMzb98rcjFYlhu0kVV6fspRhM5g',
    appId: '1:238945027859:android:a61b70f9fef90fd5a2bce6',
    messagingSenderId: '238945027859',
    projectId: 'internhub-25577',
    databaseURL: 'https://internhub-25577-default-rtdb.firebaseio.com',
    storageBucket: 'internhub-25577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5vPO6YiVMKACTIvDynZjmC30Pw9zkZA',
    appId: '1:238945027859:ios:7a52ebd20d01f478a2bce6',
    messagingSenderId: '238945027859',
    projectId: 'internhub-25577',
    databaseURL: 'https://internhub-25577-default-rtdb.firebaseio.com',
    storageBucket: 'internhub-25577.appspot.com',
    iosClientId: '238945027859-88cl76rsfdtto0c1pooohab3l87hc6bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.internhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU5vPO6YiVMKACTIvDynZjmC30Pw9zkZA',
    appId: '1:238945027859:ios:7a52ebd20d01f478a2bce6',
    messagingSenderId: '238945027859',
    projectId: 'internhub-25577',
    databaseURL: 'https://internhub-25577-default-rtdb.firebaseio.com',
    storageBucket: 'internhub-25577.appspot.com',
    iosClientId: '238945027859-88cl76rsfdtto0c1pooohab3l87hc6bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.internhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD4O-U9xtgLRDVHFETlg36cYC24hQ3wkQ',
    appId: '1:238945027859:web:7726ca5e99f84b7da2bce6',
    messagingSenderId: '238945027859',
    projectId: 'internhub-25577',
    authDomain: 'internhub-25577.firebaseapp.com',
    databaseURL: 'https://internhub-25577-default-rtdb.firebaseio.com',
    storageBucket: 'internhub-25577.appspot.com',
    measurementId: 'G-XMTC5W7CEQ',
  );

}